const deck = {
  cards: [
    {
      id: 'bX-0Fc9xMowImnN-Puh3c',
      frontSide:
        'Welcome to the SimpleCard App!\n\nThis is an example learning card. Click on it to flip it.',
      backSide:
        'Excellent!\n\nHere will be the answer to the front side\'s question. If you know the answer, click on the "Know" button or the "Don\'t know" otherwise. Known cards will appear less frequently. At this time, click on any of them.',
    },
    {
      id: 'CdUpPAJP6ijsOk0khwHSt',
      frontSide:
        'Click on the menu button in the upper right corner to open the settings panel where you can create a new deck, choose another, or edit an existing one.',
      backSide: "That's it.\n\nNow, let's get it started.",
    },
    {
      id: '97z6kwOxmBFF17r_1wLSP',
      frontSide: 'Albania',
      backSide: 'Tirana',
    },
    {
      id: 'P2SsoDnehDo9K9ee4lv_2',
      frontSide: 'Andorra',
      backSide: 'Andorra la Vella',
    },
    {
      id: 'OL2G5zV_B-k_wbwRkKPRe',
      frontSide: 'Austria',
      backSide: 'Vienna',
    },
    {
      id: '-So8v0fzhOuRXP-nRoFst',
      frontSide: 'Belarus',
      backSide: 'Minsk',
    },
    {
      id: 'tUy9iBgeTLlCldPYSKcxq',
      frontSide: 'Belgium',
      backSide: 'Brussels',
    },
    {
      id: 'Sz7hEv0iOV3CtoHFXoDz4',
      frontSide: 'Bosnia and Herzegovina',
      backSide: 'Sarajevo',
    },
    {
      id: 'E7mM7conuhMcz9p3sbIyB',
      frontSide: 'Bulgaria',
      backSide: 'Sofia',
    },
    {
      id: '_eCwYI5t7yAZ00M6vaj5O',
      frontSide: 'Croatia',
      backSide: 'Zagreb',
    },
    {
      id: 'Z2p2OWlEh4VKK2lDX2IbZ',
      frontSide: 'Czechia',
      backSide: 'Prague',
    },
    {
      id: 'lpMXSoY2cztIsUeM4eytN',
      frontSide: 'Denmark',
      backSide: 'Copenhagen',
    },
    {
      id: 'oWra_dRsYwdIfFQV-dX80',
      frontSide: 'Estonia',
      backSide: 'Tallinn',
    },
    {
      id: 'vwl4xSMFhNTtyhmdLT69_',
      frontSide: 'Finland',
      backSide: 'Helsinki',
    },
    {
      id: 'TuQTAHvEV1jZZUwKXC7ud',
      frontSide: 'France',
      backSide: 'Paris',
    },
    {
      id: 'qoIz1HD9obPOx9YGgPQFh',
      frontSide: 'Germany',
      backSide: 'Berlin',
    },
    {
      id: 'W-8JFgqaXoc0GWcl3-A5P',
      frontSide: 'Greece',
      backSide: 'Athens',
    },
    {
      id: 'no2RL5vn-coeDTxZRjFjl',
      frontSide: 'Hungary',
      backSide: 'Budapest',
    },
    {
      id: 'kwzM96gM2nZk5iSGnMbkZ',
      frontSide: 'Iceland',
      backSide: 'Reykjavik',
    },
    {
      id: 'b3yBQTOmB4rAu9hb8kYzW',
      frontSide: 'Ireland',
      backSide: 'Dublin',
    },
    {
      id: 'Ca8H_r-VhsQbjI0BQwIOI',
      frontSide: 'Italy',
      backSide: 'Rome',
    },
    {
      id: 'd82O-M5tY4ogt5CR3SYWT',
      frontSide: 'Latvia',
      backSide: 'Riga',
    },
    {
      id: 'cVVvEzJXBc3HlOBNb7LY2',
      frontSide: 'Liechtenstein',
      backSide: 'Vaduz',
    },
    {
      id: 'ZWGuq-u43a8njzVQpivqG',
      frontSide: 'Lithuania',
      backSide: 'Vilnius',
    },
    {
      id: 'ZyzVXRV6vmEKrzWbAT5hp',
      frontSide: 'Luxembourg',
      backSide: 'Luxembourg',
    },
    {
      id: 'rAByuT_N_vmOiaoubTcPo',
      frontSide: 'Malta',
      backSide: 'Valletta',
    },
    {
      id: '943AEqlI2vz_eB23cufse',
      frontSide: 'Moldova',
      backSide: 'Chisinau',
    },
    {
      id: 'vmvoEG0I9CShMiJdi06ez',
      frontSide: 'Monaco',
      backSide: 'Monaco',
    },
    {
      id: 'eVNPBOhlxuJeazZF1Xr-t',
      frontSide: 'Montenegro',
      backSide: 'Podgorica',
    },
    {
      id: 'hr8mpnWS1V7s59cCwyiLH',
      frontSide: 'Netherlands',
      backSide: 'Amsterdam',
    },
    {
      id: 'iqnP2m5ZGv3h6-lJaqNc1',
      frontSide: 'North Macedonia',
      backSide: 'Skopje',
    },
    {
      id: 'qaFN1dVr_3eZ5S3PRm_cZ',
      frontSide: 'Norway',
      backSide: 'Oslo',
    },
    {
      id: 'tkCejcafuhRHyRr5Y4l1O',
      frontSide: 'Poland',
      backSide: 'Warsaw',
    },
    {
      id: 'dsUeanEXBoI9bvaVdi5nw',
      frontSide: 'Portugal',
      backSide: 'Lisbon',
    },
    {
      id: 'Qa3YuOkdKaVD0-g8Xh-8C',
      frontSide: 'Romania',
      backSide: 'Bucharest',
    },
    {
      id: 'ZeH1QboXor4QAjRQz_JOr',
      frontSide: 'Russia',
      backSide: 'Moscow',
    },
    {
      id: 'HEhr_tdTn1sDnoRrhYiw2',
      frontSide: 'San Marino',
      backSide: 'San Marino',
    },
    {
      id: 'psINX9LEuGv603Xdh3D9s',
      frontSide: 'Serbia',
      backSide: 'Belgrade',
    },
    {
      id: 'wsuS0-OAX2m13ex_Ssm9K',
      frontSide: 'Slovakia',
      backSide: 'Bratislava',
    },
    {
      id: 'qvCYF6ha-T8B7-PFfZd_6',
      frontSide: 'Slovenia',
      backSide: 'Ljubljana',
    },
    {
      id: '_DKDJTBc7BCRd34-jiv1T',
      frontSide: 'Spain',
      backSide: 'Madrid',
    },
    {
      id: 'dSxDu5k3j_RnJfUuMZf60',
      frontSide: 'Sweden',
      backSide: 'Stockholm',
    },
    {
      id: 'FikmfV6UtUFFc5VLfM2ny',
      frontSide: 'Switzerland',
      backSide: 'Bern',
    },
    {
      id: 'U65Rs8fEw7Y7iDG6XvugZ',
      frontSide: 'Ukraine',
      backSide: 'Kiev',
    },
    {
      id: 'oBiu0Aczia_Xiz5x3CnPK',
      frontSide: 'United Kingdom',
      backSide: 'London',
    },
  ],
  cardsByBoxes: {
    'bX-0Fc9xMowImnN-Puh3c': 1,
    CdUpPAJP6ijsOk0khwHSt: 1,
    '97z6kwOxmBFF17r_1wLSP': 1,
    P2SsoDnehDo9K9ee4lv_2: 1,
    'OL2G5zV_B-k_wbwRkKPRe': 1,
    '-So8v0fzhOuRXP-nRoFst': 1,
    tUy9iBgeTLlCldPYSKcxq: 1,
    Sz7hEv0iOV3CtoHFXoDz4: 1,
    E7mM7conuhMcz9p3sbIyB: 1,
    _eCwYI5t7yAZ00M6vaj5O: 1,
    Z2p2OWlEh4VKK2lDX2IbZ: 1,
    lpMXSoY2cztIsUeM4eytN: 1,
    'oWra_dRsYwdIfFQV-dX80': 1,
    vwl4xSMFhNTtyhmdLT69_: 1,
    TuQTAHvEV1jZZUwKXC7ud: 1,
    qoIz1HD9obPOx9YGgPQFh: 1,
    'W-8JFgqaXoc0GWcl3-A5P': 1,
    'no2RL5vn-coeDTxZRjFjl': 1,
    kwzM96gM2nZk5iSGnMbkZ: 1,
    b3yBQTOmB4rAu9hb8kYzW: 1,
    'Ca8H_r-VhsQbjI0BQwIOI': 1,
    'd82O-M5tY4ogt5CR3SYWT': 1,
    cVVvEzJXBc3HlOBNb7LY2: 1,
    'ZWGuq-u43a8njzVQpivqG': 1,
    ZyzVXRV6vmEKrzWbAT5hp: 1,
    rAByuT_N_vmOiaoubTcPo: 1,
    '943AEqlI2vz_eB23cufse': 1,
    vmvoEG0I9CShMiJdi06ez: 1,
    'eVNPBOhlxuJeazZF1Xr-t': 1,
    hr8mpnWS1V7s59cCwyiLH: 1,
    'iqnP2m5ZGv3h6-lJaqNc1': 1,
    qaFN1dVr_3eZ5S3PRm_cZ: 1,
    tkCejcafuhRHyRr5Y4l1O: 1,
    dsUeanEXBoI9bvaVdi5nw: 1,
    'Qa3YuOkdKaVD0-g8Xh-8C': 1,
    ZeH1QboXor4QAjRQz_JOr: 1,
    HEhr_tdTn1sDnoRrhYiw2: 1,
    psINX9LEuGv603Xdh3D9s: 1,
    'wsuS0-OAX2m13ex_Ssm9K': 1,
    'qvCYF6ha-T8B7-PFfZd_6': 1,
    '_DKDJTBc7BCRd34-jiv1T': 1,
    dSxDu5k3j_RnJfUuMZf60: 1,
    FikmfV6UtUFFc5VLfM2ny: 1,
    U65Rs8fEw7Y7iDG6XvugZ: 1,
    oBiu0Aczia_Xiz5x3CnPK: 1,
  },
  drawCounter: 1,
  id: 'VsXTzQr7IwjDfFFTIwZJO',
  sessionCounter: 1,
  sessionFinished: false,
  numberOfSessionCards: 45,
  title: 'Example cards - European capitals',
  lastCard: 'bX-0Fc9xMowImnN-Puh3c',
};

export default deck;
